/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as SupportInboxRouteImport } from './routes/support-inbox'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MixmanRouteImport } from './routes/mixman'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTokensRouteImport } from './routes/api/tokens'
import { Route as ApiTokenMetaRouteImport } from './routes/api/token-meta'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'
import { Route as ApiBalanceRouteImport } from './routes/api/balance'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as ApiPublicVisitRouteImport } from './routes/api/public/visit'
import { Route as ApiPublicThirdwebConfigRouteImport } from './routes/api/public/thirdweb-config'
import { Route as ApiPublicNotifyRouteImport } from './routes/api/public/notify'
import { Route as ApiPublicAlertRouteImport } from './routes/api/public/alert'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportInboxRoute = SupportInboxRouteImport.update({
  id: '/support-inbox',
  path: '/support-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MixmanRoute = MixmanRouteImport.update({
  id: '/mixman',
  path: '/mixman',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api/tokens',
  path: '/api/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenMetaRoute = ApiTokenMetaRouteImport.update({
  id: '/api/token-meta',
  path: '/api/token-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBalanceRoute = ApiBalanceRouteImport.update({
  id: '/api/balance',
  path: '/api/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVisitRoute = ApiPublicVisitRouteImport.update({
  id: '/api/public/visit',
  path: '/api/public/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicThirdwebConfigRoute = ApiPublicThirdwebConfigRouteImport.update({
  id: '/api/public/thirdweb-config',
  path: '/api/public/thirdweb-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyRoute = ApiPublicNotifyRouteImport.update({
  id: '/api/public/notify',
  path: '/api/public/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlertRoute = ApiPublicAlertRouteImport.update({
  id: '/api/public/alert',
  path: '/api/public/alert',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/mixman': typeof MixmanRoute
  '/news': typeof NewsRoute
  '/support-inbox': typeof SupportInboxRoute
  '/swap': typeof SwapRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/token-meta': typeof ApiTokenMetaRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/public/alert': typeof ApiPublicAlertRoute
  '/api/public/notify': typeof ApiPublicNotifyRoute
  '/api/public/thirdweb-config': typeof ApiPublicThirdwebConfigRoute
  '/api/public/visit': typeof ApiPublicVisitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/mixman': typeof MixmanRoute
  '/news': typeof NewsRoute
  '/support-inbox': typeof SupportInboxRoute
  '/swap': typeof SwapRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/token-meta': typeof ApiTokenMetaRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/public/alert': typeof ApiPublicAlertRoute
  '/api/public/notify': typeof ApiPublicNotifyRoute
  '/api/public/thirdweb-config': typeof ApiPublicThirdwebConfigRoute
  '/api/public/visit': typeof ApiPublicVisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/mixman': typeof MixmanRoute
  '/news': typeof NewsRoute
  '/support-inbox': typeof SupportInboxRoute
  '/swap': typeof SwapRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/token-meta': typeof ApiTokenMetaRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/public/alert': typeof ApiPublicAlertRoute
  '/api/public/notify': typeof ApiPublicNotifyRoute
  '/api/public/thirdweb-config': typeof ApiPublicThirdwebConfigRoute
  '/api/public/visit': typeof ApiPublicVisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/how-it-works'
    | '/markets'
    | '/mixman'
    | '/news'
    | '/support-inbox'
    | '/swap'
    | '/trade'
    | '/wallet'
    | '/api/activity'
    | '/api/balance'
    | '/api/markets'
    | '/api/news'
    | '/api/token-meta'
    | '/api/tokens'
    | '/api/public/alert'
    | '/api/public/notify'
    | '/api/public/thirdweb-config'
    | '/api/public/visit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/how-it-works'
    | '/markets'
    | '/mixman'
    | '/news'
    | '/support-inbox'
    | '/swap'
    | '/trade'
    | '/wallet'
    | '/api/activity'
    | '/api/balance'
    | '/api/markets'
    | '/api/news'
    | '/api/token-meta'
    | '/api/tokens'
    | '/api/public/alert'
    | '/api/public/notify'
    | '/api/public/thirdweb-config'
    | '/api/public/visit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/how-it-works'
    | '/markets'
    | '/mixman'
    | '/news'
    | '/support-inbox'
    | '/swap'
    | '/trade'
    | '/wallet'
    | '/api/activity'
    | '/api/balance'
    | '/api/markets'
    | '/api/news'
    | '/api/token-meta'
    | '/api/tokens'
    | '/api/public/alert'
    | '/api/public/notify'
    | '/api/public/thirdweb-config'
    | '/api/public/visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketsRoute: typeof MarketsRoute
  MixmanRoute: typeof MixmanRoute
  NewsRoute: typeof NewsRoute
  SupportInboxRoute: typeof SupportInboxRoute
  SwapRoute: typeof SwapRoute
  TradeRoute: typeof TradeRoute
  WalletRoute: typeof WalletRoute
  ApiActivityRoute: typeof ApiActivityRoute
  ApiBalanceRoute: typeof ApiBalanceRoute
  ApiMarketsRoute: typeof ApiMarketsRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiTokenMetaRoute: typeof ApiTokenMetaRoute
  ApiTokensRoute: typeof ApiTokensRoute
  ApiPublicAlertRoute: typeof ApiPublicAlertRoute
  ApiPublicNotifyRoute: typeof ApiPublicNotifyRoute
  ApiPublicThirdwebConfigRoute: typeof ApiPublicThirdwebConfigRoute
  ApiPublicVisitRoute: typeof ApiPublicVisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-inbox': {
      id: '/support-inbox'
      path: '/support-inbox'
      fullPath: '/support-inbox'
      preLoaderRoute: typeof SupportInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mixman': {
      id: '/mixman'
      path: '/mixman'
      fullPath: '/mixman'
      preLoaderRoute: typeof MixmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens': {
      id: '/api/tokens'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token-meta': {
      id: '/api/token-meta'
      path: '/api/token-meta'
      fullPath: '/api/token-meta'
      preLoaderRoute: typeof ApiTokenMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/balance': {
      id: '/api/balance'
      path: '/api/balance'
      fullPath: '/api/balance'
      preLoaderRoute: typeof ApiBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/visit': {
      id: '/api/public/visit'
      path: '/api/public/visit'
      fullPath: '/api/public/visit'
      preLoaderRoute: typeof ApiPublicVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/thirdweb-config': {
      id: '/api/public/thirdweb-config'
      path: '/api/public/thirdweb-config'
      fullPath: '/api/public/thirdweb-config'
      preLoaderRoute: typeof ApiPublicThirdwebConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify': {
      id: '/api/public/notify'
      path: '/api/public/notify'
      fullPath: '/api/public/notify'
      preLoaderRoute: typeof ApiPublicNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alert': {
      id: '/api/public/alert'
      path: '/api/public/alert'
      fullPath: '/api/public/alert'
      preLoaderRoute: typeof ApiPublicAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketsRoute: MarketsRoute,
  MixmanRoute: MixmanRoute,
  NewsRoute: NewsRoute,
  SupportInboxRoute: SupportInboxRoute,
  SwapRoute: SwapRoute,
  TradeRoute: TradeRoute,
  WalletRoute: WalletRoute,
  ApiActivityRoute: ApiActivityRoute,
  ApiBalanceRoute: ApiBalanceRoute,
  ApiMarketsRoute: ApiMarketsRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiTokenMetaRoute: ApiTokenMetaRoute,
  ApiTokensRoute: ApiTokensRoute,
  ApiPublicAlertRoute: ApiPublicAlertRoute,
  ApiPublicNotifyRoute: ApiPublicNotifyRoute,
  ApiPublicThirdwebConfigRoute: ApiPublicThirdwebConfigRoute,
  ApiPublicVisitRoute: ApiPublicVisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
